! Portable bundled example. All paths are relative to this configuration file.
year               2026
doy_start          150
doy_end            150
antfile            data/ant/igs20.atx
reference_ac       COD
reference_orbit    SP3
reference_clock    CLK
reference_dir      data/cod
compared_ac        B2b
compared_orbit     SP3
compared_clock     CLK
compared_dir       data/b2b
reference_bdsfreq  B1B2
compared_bdsfreq   B1B2
interval(s)        30
mode               both
systemused         C
clkdatum           R-C
clkdatum_method    CMED
outdir             ../output/regional_cmed
is_cnav            false
ssrcorrtype        0
