! Portable bundled example. All paths are relative to this configuration file.
year               2026
doy_start          197
doy_end            197
antfile            data/ant/igs20.atx
reference_ac       gbm
reference_orbit    SP3
reference_clock    CLK
reference_dir      data/gbm
compared_ac        
compared_orbit     BRDM
compared_clock     BRDM
compared_dir       data/nav
reference_bdsfreq  B1B2
compared_bdsfreq   B1B2
interval(s)        30
mode               both
systemused         C
clkdatum           CLK
clkdatum_method    CMED
outdir             ../output/ssr_shao
is_cnav            false
ssrcorrtype        2
dcbdir             data/bias
DCBtype            GFZ0OPSRAP.BIA
ssr_ref            B1I_APC
ssrdir             data/ssr
ssr_format         SSRA01SHA0ddd0.yyC
ssrage             30
